apiVersion: v1
kind: Template
metadata:
  name: mq-secret
objects:
- kind: Secret
  apiVersion: v1
  metadata:
    name: ${PREFIX}-mq-key-cert
    namespace: ${NAMESPACE}
  data:
    ${PREFIX}-mq-server.crt: ${MQ_SERVER_CERT}
    ${PREFIX}-mq-server.key: ${MQ_SERVER_KEY}
- kind: Secret
  apiVersion: v1
  metadata:
    name: ${PREFIX}-ca-cert
    namespace: ${NAMESPACE}
  data:
    ${PREFIX}-ca.crt: ${CA_CERT}
parameters:
  - name: NAMESPACE
  - name: PREFIX
  - name: MQ_SERVER_CERT
  - name: MQ_SERVER_KEY
  - name: CA_CERT